# Clasificación de razas con Oxford IIIT Pet

## Actividad grupal de Redes Neuronales Convolucionales

Este notebook implementa un estudio experimental reproducible para clasificar las **37 razas** del Oxford-IIIT Pet Dataset. La entrega compara un baseline Fully Connected, arquitecturas CNN propias, una ablación controlada de data augmentation y dos etapas de transfer learning con MobileNetV2.

**Objetivo verificable:** seleccionar el modelo únicamente con datos de validación y comprobar al final si supera **85% de accuracy en test** sin evidencia relevante de overfitting ni underfitting. El notebook no contiene métricas inventadas: todas las tablas, figuras y conclusiones se generan a partir de la ejecución real.

## Metodología y reglas del experimento

1. Se fija una semilla global y se registra el entorno de ejecución.
2. Se corrige el split suministrado: `train[:80]` seleccionaba 80 imágenes, no 80%. Se usa `train[:80%]`, `train[80%:90%]` y `train[90%:]`.
3. Las imágenes se redimensionan a 160 por 160 y se normalizan al intervalo [0, 1].
4. Train y validation se utilizan para aprender, ajustar y seleccionar. **Test permanece cerrado** hasta finalizar la selección.
5. Todos los experimentos guardan el mejor checkpoint por `val_accuracy`, su historial y su configuración.
6. El modelo final se juzga con accuracy, precision, recall, F1, matriz de confusión, curvas y análisis visual de errores.

La comparación `cnn_regularized_no_aug` frente a `cnn_regularized_aug` mantiene igual arquitectura, optimizador y regularización. La única diferencia es el aumento de datos, por lo que funciona como una ablación interpretable.

## 1 Librerías y configuración

En Google Colab las dependencias principales suelen estar instaladas. Si una importación falla, ejecute antes:

```python
%pip install -q -r requirements.txt
```

Si abrió el notebook directamente desde GitHub y `requirements.txt` no está en el entorno de Colab, use:

```python
%pip install -q "tensorflow-datasets>=4.9,<5" "protobuf>=6.31,<7" "seaborn>=0.13,<1" "scikit-learn>=1.4,<2"
```

Después de una instalación que cambie TensorFlow o Protobuf, reinicie el entorno de ejecución antes de continuar.

In [1]:
import json
import os
import platform
import random
import shutil
import sys
import time
import warnings
from collections import OrderedDict
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import sklearn
import tensorflow as tf
import tensorflow_datasets as tfds
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow import keras
from tensorflow.keras import layers

warnings.filterwarnings("ignore", category=UserWarning)
sns.set_theme(style="whitegrid", context="notebook")
print("TensorFlow:", tf.__version__)
print("TensorFlow Datasets:", tfds.__version__)
print("Python:", sys.version.split()[0])
print("Aceleradores:", tf.config.list_physical_devices("GPU"))

TensorFlow: 2.18.1
TensorFlow Datasets: 4.9.10
Python: 3.12.14
Aceleradores: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [2]:
# Configuración central. FAST_MODE solo sirve para verificar el flujo.
SEED = 42
IMG_SIZE = 160
BATCH_SIZE = 32
FAST_MODE = False
USE_GOOGLE_DRIVE = False
FORCE_RETRAIN = False
RUN_TRAINING = True

random.seed(SEED)
np.random.seed(SEED)
tf.keras.utils.set_random_seed(SEED)

try:
    tf.config.experimental.enable_op_determinism()
    DETERMINISM = True
except Exception:
    DETERMINISM = False

if USE_GOOGLE_DRIVE:
    from google.colab import drive
    drive.mount("/content/drive")
    WORK_ROOT = Path("/content/drive/MyDrive/oxford_pet_assignment")
else:
    WORK_ROOT = Path.cwd()

MODEL_DIR = WORK_ROOT / "models"
ARTIFACT_DIR = WORK_ROOT / "artifacts"
MODEL_DIR.mkdir(parents=True, exist_ok=True)
ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)

CONFIG = {
    "seed": SEED,
    "image_size": IMG_SIZE,
    "batch_size": BATCH_SIZE,
    "fast_mode": FAST_MODE,
    "deterministic_ops": DETERMINISM,
    "tensorflow": tf.__version__,
    "tensorflow_datasets": tfds.__version__,
    "python": sys.version,
    "platform": platform.platform(),
    "gpu_devices": [device.name for device in tf.config.list_physical_devices("GPU")],
}
(ARTIFACT_DIR / "run_config.json").write_text(
    json.dumps(CONFIG, indent=2, ensure_ascii=False), encoding="utf-8"
)
CONFIG

{'seed': 42,
 'image_size': 160,
 'batch_size': 32,
 'fast_mode': False,
 'deterministic_ops': True,
 'tensorflow': '2.18.1',
 'tensorflow_datasets': '4.9.10',
 'python': '3.12.14 (main, Aug 25 2026, 13:50:33) [Clang 22.1.3 ]',
 'platform': 'macOS-26.4.1-arm64-arm-64bit',
 'gpu_devices': ['/physical_device:GPU:0']}

## 2 Dataset y partición

Oxford-IIIT Pet contiene imágenes RGB y etiquetas de raza. El split de trabajo conserva el esquema 80/10/10 de la plantilla. En modo completo se esperan aproximadamente 2,944 imágenes para train, 368 para validation y 368 para test.

**Corrección importante:** `train[:80]` significa “las primeras 80 observaciones”. El símbolo `%` es indispensable para utilizar el 80%.

In [3]:
if FAST_MODE:
    split_spec = ["train[:10%]", "train[80%:82%]", "train[90%:92%]"]
else:
    split_spec = ["train[:80%]", "train[80%:90%]", "train[90%:]"]

read_config = tfds.ReadConfig(shuffle_seed=SEED)
(raw_train, raw_val, raw_test), dataset_info = tfds.load(
    "oxford_iiit_pet",
    split=split_spec,
    as_supervised=True,
    with_info=True,
    shuffle_files=True,
    read_config=read_config,
)

CLASS_NAMES = dataset_info.features["label"].names
NUM_CLASSES = dataset_info.features["label"].num_classes

def cardinality(dataset):
    value = tf.data.experimental.cardinality(dataset).numpy()
    return int(value) if value >= 0 else sum(1 for _ in dataset)

split_sizes = {
    "train": cardinality(raw_train),
    "validation": cardinality(raw_val),
    "test": cardinality(raw_test),
}
assert NUM_CLASSES == 37, f"Se esperaban 37 clases y se encontraron {NUM_CLASSES}"
assert all(size > 0 for size in split_sizes.values())
print("Clases:", NUM_CLASSES)
print("Tamaños:", split_sizes)
print("Primeras clases:", CLASS_NAMES[:5])

Clases: 37
Tamaños: {'train': 2944, 'validation': 368, 'test': 368}
Primeras clases: ['Abyssinian', 'american_bulldog', 'american_pit_bull_terrier', 'basset_hound', 'beagle']

2026-09-11 22:51:50.162807: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M5
2026-09-11 22:51:50.162845: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2026-09-11 22:51:50.162852: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.92 GB
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1789188710.162866 28463986 pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
I0000 00:00:1789188710.162884 28463986 pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)

In [4]:
AUTOTUNE = tf.data.AUTOTUNE

def preprocess_image(image, label):
    image = tf.image.resize(image, (IMG_SIZE, IMG_SIZE), antialias=True)
    image = tf.cast(image, tf.float32) / 255.0
    # La interpolación con antialias puede producir diferencias de coma
    # flotante mínimas fuera del intervalo; se fuerza el contrato [0, 1].
    image = tf.clip_by_value(image, 0.0, 1.0)
    label = tf.cast(label, tf.int32)
    return image, label

def prepare_dataset(dataset, training=False):
    dataset = dataset.map(preprocess_image, num_parallel_calls=AUTOTUNE)
    if training:
        dataset = dataset.shuffle(
            min(split_sizes["train"], 2_000),
            seed=SEED,
            reshuffle_each_iteration=True,
        )
    return dataset.batch(BATCH_SIZE).prefetch(AUTOTUNE)

train_batches = prepare_dataset(raw_train, training=True)
val_batches = prepare_dataset(raw_val)
test_batches = prepare_dataset(raw_test)

sample_images, sample_labels = next(iter(train_batches))
assert sample_images.shape[1:] == (IMG_SIZE, IMG_SIZE, 3)
assert float(tf.reduce_min(sample_images)) >= 0.0
assert float(tf.reduce_max(sample_images)) <= 1.0
print("Batch de imágenes:", sample_images.shape)
print("Batch de etiquetas:", sample_labels.shape)

2026-09-11 22:51:50.303446: I tensorflow/core/kernels/data/tf_record_dataset_op.cc:376] The default buffer size is 262144, which is overridden by the user specified `buffer_size` of 8388608

Batch de imágenes: (32, 160, 160, 3)
Batch de etiquetas: (32,)

## 3 Análisis exploratorio

Se inspeccionan tamaño, balance por clase y ejemplos representativos. Las clases tienen nombres de razas; algunas son visualmente similares, de modo que una accuracy global debe complementarse con métricas por clase y análisis de confusiones.

In [5]:
def label_counts(dataset):
    labels = np.fromiter((int(label.numpy()) for _, label in dataset), dtype=np.int32)
    counts = np.bincount(labels, minlength=NUM_CLASSES)
    return pd.DataFrame({"class_id": range(NUM_CLASSES), "class_name": CLASS_NAMES, "count": counts})

train_distribution = label_counts(raw_train)
val_distribution = label_counts(raw_val)
test_distribution = label_counts(raw_test)

distribution_summary = pd.DataFrame({
    "split": ["train", "validation", "test"],
    "images": [len(train_distribution) and train_distribution["count"].sum(),
               len(val_distribution) and val_distribution["count"].sum(),
               len(test_distribution) and test_distribution["count"].sum()],
    "min_per_class": [train_distribution["count"].min(), val_distribution["count"].min(), test_distribution["count"].min()],
    "max_per_class": [train_distribution["count"].max(), val_distribution["count"].max(), test_distribution["count"].max()],
})
display(distribution_summary)
display(train_distribution.sort_values("count").head(10))
train_distribution.to_csv(ARTIFACT_DIR / "class_distribution_train.csv", index=False)

2026-09-11 22:51:51.813100: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-11 22:51:51.916389: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence

        split  images  min_per_class  max_per_class
0       train    2944             70             87
1  validation     368              4             17
2        test     368              4             16

    class_id              class_name  count
33        33                  Sphynx     70
11        11            Egyptian_Mau     71
28        28           saint_bernard     72
12        12  english_cocker_spaniel     73
29        29                 samoyed     74
0          0              Abyssinian     76
8          8                   boxer     76
24        24              pomeranian     76
6          6                  Birman     76
17        17           japanese_chin     76

In [6]:
fig, axes = plt.subplots(1, 2, figsize=(18, 7))

ordered = train_distribution.sort_values("count")
axes[0].barh(ordered["class_name"], ordered["count"], color="#3b82f6")
axes[0].set_title("Distribución de clases en train")
axes[0].set_xlabel("Número de imágenes")

preview_images, preview_labels = next(iter(prepare_dataset(raw_train.take(12))))
axes[1].axis("off")
axes[1].set_title("La galería se muestra en la figura siguiente")
plt.tight_layout()
fig.savefig(ARTIFACT_DIR / "eda_class_distribution.png", dpi=160, bbox_inches="tight")
plt.show()

fig, axes = plt.subplots(3, 4, figsize=(12, 10))
for ax, image, label in zip(axes.flat, preview_images, preview_labels):
    ax.imshow(image)
    ax.set_title(CLASS_NAMES[int(label)])
    ax.axis("off")
plt.tight_layout()
fig.savefig(ARTIFACT_DIR / "eda_examples.png", dpi=160, bbox_inches="tight")
plt.show()

### Interpretación del EDA

La tabla permite verificar de forma cuantitativa si el corte porcentual introduce desbalance relevante. Aunque el dataset completo contiene cerca de 200 imágenes por raza, este trabajo usa el split `train` suministrado y reserva parte de él para validación y test. La variación de pose, escala, iluminación, fondo y encuadre aumenta la dificultad; además, varias razas comparten color, textura y morfología.

No se aplica oversampling antes de observar las métricas. Data augmentation se estudia mediante una comparación controlada, y las métricas macro evitan que una clase frecuente domine la conclusión.

## 4 Diseño experimental

| Experimento | Arquitectura | Augmentation | Regularización | Propósito |
|---|---|---|---|---|
| `fc_baseline` | Flatten y Dense | No | Dropout | Baseline sin sesgo espacial |
| `cnn_baseline` | 3 bloques Conv2D | No | No | Aporte básico de convoluciones |
| `cnn_regularized_no_aug` | CNN propia profunda | No | BN y Dropout | Efecto de arquitectura y regularización |
| `cnn_regularized_aug` | Misma CNN propia | Sí | BN y Dropout | Ablación del augmentation |
| `mobilenet_transfer` | MobileNetV2 congelada | Sí | Dropout | Transfer learning |
| `mobilenet_finetuned` | MobileNetV2 parcial | Sí | Dropout y LR bajo | Adaptación final al dominio |

Todos usan sparse categorical cross-entropy y Adam. Las épocas máximas no son equivalentes a épocas efectivas porque EarlyStopping detiene el entrenamiento cuando validation deja de mejorar.

In [7]:
DATA_AUGMENTATION = keras.Sequential(
    [
        layers.RandomFlip("horizontal", seed=SEED),
        layers.RandomRotation(0.08, fill_mode="reflect", seed=SEED + 1),
        layers.RandomZoom(0.12, fill_mode="reflect", seed=SEED + 2),
        layers.RandomTranslation(0.08, 0.08, fill_mode="reflect", seed=SEED + 3),
        layers.RandomContrast(0.10, seed=SEED + 4),
    ],
    name="data_augmentation",
)

def compile_model(model, learning_rate):
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=learning_rate),
        loss=keras.losses.SparseCategoricalCrossentropy(),
        metrics=[keras.metrics.SparseCategoricalAccuracy(name="accuracy")],
    )
    return model

def conv_block(x, filters, dropout=0.0):
    x = layers.Conv2D(filters, 3, padding="same", use_bias=False)(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)
    x = layers.Conv2D(filters, 3, padding="same", use_bias=False)(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)
    x = layers.MaxPooling2D()(x)
    if dropout:
        x = layers.SpatialDropout2D(dropout)(x)
    return x

def build_fully_connected():
    inputs = keras.Input((IMG_SIZE, IMG_SIZE, 3))
    x = layers.Resizing(64, 64)(inputs)
    x = layers.Flatten()(x)
    x = layers.Dense(128, activation="relu")(x)
    x = layers.Dropout(0.45)(x)
    outputs = layers.Dense(NUM_CLASSES, activation="softmax")(x)
    return keras.Model(inputs, outputs, name="fc_baseline")

def build_cnn_baseline():
    inputs = keras.Input((IMG_SIZE, IMG_SIZE, 3))
    x = inputs
    for filters in (32, 64, 128):
        x = layers.Conv2D(filters, 3, padding="same", activation="relu")(x)
        x = layers.MaxPooling2D()(x)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dense(128, activation="relu")(x)
    outputs = layers.Dense(NUM_CLASSES, activation="softmax")(x)
    return keras.Model(inputs, outputs, name="cnn_baseline")

def build_regularized_cnn(use_augmentation):
    inputs = keras.Input((IMG_SIZE, IMG_SIZE, 3))
    x = DATA_AUGMENTATION(inputs) if use_augmentation else inputs
    x = conv_block(x, 32, 0.05)
    x = conv_block(x, 64, 0.10)
    x = conv_block(x, 128, 0.15)
    x = conv_block(x, 256, 0.20)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dense(256, use_bias=False)(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)
    x = layers.Dropout(0.45)(x)
    outputs = layers.Dense(NUM_CLASSES, activation="softmax")(x)
    suffix = "aug" if use_augmentation else "no_aug"
    return keras.Model(inputs, outputs, name=f"cnn_regularized_{suffix}")

def build_mobilenet_transfer():
    inputs = keras.Input((IMG_SIZE, IMG_SIZE, 3))
    x = DATA_AUGMENTATION(inputs)
    # El pipeline entrega [0,1]; MobileNetV2 fue entrenada con [-1,1].
    x = layers.Rescaling(2.0, offset=-1.0, name="mobilenet_normalization")(x)
    backbone = keras.applications.MobileNetV2(
        input_shape=(IMG_SIZE, IMG_SIZE, 3),
        include_top=False,
        weights="imagenet",
    )
    backbone.trainable = False
    x = backbone(x, training=False)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dropout(0.35)(x)
    outputs = layers.Dense(NUM_CLASSES, activation="softmax")(x)
    return keras.Model(inputs, outputs, name="mobilenet_transfer")

## 5 Utilidades de entrenamiento y trazabilidad

Cada corrida persiste el mejor modelo completo, historial, log por época y metadatos. Si el checkpoint existe y `FORCE_RETRAIN` es falso, se carga en vez de entrenarse de nuevo. Esto permite retomar una sesión y realizar predicciones sin GPU.

In [8]:
EXPERIMENT_CONFIG = OrderedDict({
    "fc_baseline": {"epochs": 18, "lr": 1e-3, "patience": 5},
    "cnn_baseline": {"epochs": 30, "lr": 1e-3, "patience": 6},
    "cnn_regularized_no_aug": {"epochs": 35, "lr": 7e-4, "patience": 7},
    "cnn_regularized_aug": {"epochs": 40, "lr": 7e-4, "patience": 8},
    "mobilenet_transfer": {"epochs": 20, "lr": 1e-3, "patience": 5},
    "mobilenet_finetuned": {"epochs": 20, "lr": 1e-5, "patience": 6},
})

if FAST_MODE:
    for config in EXPERIMENT_CONFIG.values():
        config["epochs"] = 2
        config["patience"] = 1

models = OrderedDict()
histories = OrderedDict()
durations = OrderedDict()

def experiment_paths(name):
    return {
        "model": MODEL_DIR / f"{name}.keras",
        "history": ARTIFACT_DIR / f"{name}_history.json",
        "log": ARTIFACT_DIR / f"{name}_epochs.csv",
    }

def make_callbacks(name, config):
    paths = experiment_paths(name)
    return [
        keras.callbacks.ModelCheckpoint(
            paths["model"], monitor="val_accuracy", mode="max", save_best_only=True, verbose=1
        ),
        keras.callbacks.EarlyStopping(
            monitor="val_accuracy", mode="max", patience=config["patience"], restore_best_weights=True, verbose=1
        ),
        keras.callbacks.ReduceLROnPlateau(
            monitor="val_loss", mode="min", factor=0.3, patience=max(2, config["patience"] // 2), min_lr=1e-7, verbose=1
        ),
        keras.callbacks.CSVLogger(paths["log"]),
        keras.callbacks.TerminateOnNaN(),
    ]

def save_history(name, history_dict):
    serializable = {key: [float(value) for value in values] for key, values in history_dict.items()}
    experiment_paths(name)["history"].write_text(
        json.dumps(serializable, indent=2), encoding="utf-8"
    )
    return serializable

def train_or_load(name, builder):
    config = EXPERIMENT_CONFIG[name]
    paths = experiment_paths(name)
    if paths["model"].exists() and not FORCE_RETRAIN:
        print(f"Cargando checkpoint existente: {paths['model']}")
        model = keras.models.load_model(paths["model"], compile=False)
        model = compile_model(model, config["lr"])
        history = json.loads(paths["history"].read_text()) if paths["history"].exists() else {}
        duration = np.nan
    else:
        if not RUN_TRAINING:
            raise FileNotFoundError(f"No existe {paths['model']} y RUN_TRAINING=False")
        tf.keras.backend.clear_session()
        tf.keras.utils.set_random_seed(SEED)
        model = compile_model(builder(), config["lr"])
        print(f"\nEntrenando {name} con {model.count_params():,} parámetros")
        started = time.perf_counter()
        fitted = model.fit(
            train_batches,
            validation_data=val_batches,
            epochs=config["epochs"],
            callbacks=make_callbacks(name, config),
            verbose=2,
        )
        duration = time.perf_counter() - started
        history = save_history(name, fitted.history)
        model = keras.models.load_model(paths["model"], compile=False)
        model = compile_model(model, config["lr"])
    models[name] = model
    histories[name] = history
    durations[name] = duration
    return model

EXPERIMENT_CONFIG

OrderedDict([('fc_baseline', {'epochs': 18, 'lr': 0.001, 'patience': 5}),
             ('cnn_baseline', {'epochs': 30, 'lr': 0.001, 'patience': 6}),
             ('cnn_regularized_no_aug',
              {'epochs': 35, 'lr': 0.0007, 'patience': 7}),
             ('cnn_regularized_aug',
              {'epochs': 40, 'lr': 0.0007, 'patience': 8}),
             ('mobilenet_transfer',
              {'epochs': 20, 'lr': 0.001, 'patience': 5}),
             ('mobilenet_finetuned',
              {'epochs': 20, 'lr': 1e-05, 'patience': 6})])

## 6 Experimento Fully Connected

El baseline aplana una versión 64 por 64 para mantener un número razonable de parámetros. Al perder explícitamente la vecindad espacial, sirve para contrastar la inductive bias de las convoluciones.

In [9]:
fc_model = train_or_load("fc_baseline", build_fully_connected)
fc_model.summary()

Entrenando fc_baseline con 1,577,765 parámetros
Epoch 1/18

2026-09-11 22:51:52.875851: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.

Epoch 1: val_accuracy improved from None to 0.03533, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/fc_baseline.keras

Epoch 1: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/fc_baseline.keras

92/92 - 3s - 32ms/step - accuracy: 0.0326 - loss: 53.9470 - val_accuracy: 0.0353 - val_loss: 12.6174 - learning_rate: 0.0010

Epoch 2/18

Epoch 2: val_accuracy improved from 0.03533 to 0.07337, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/fc_baseline.keras

Epoch 2: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/fc_baseline.keras

92/92 - 3s - 28ms/step - accuracy: 0.0289 - loss: 56.2077 - val_accuracy: 0.0734 - val_loss: 11.0639 - learning_rate: 0.0010

Epoch 3/18

Epoch 3: val_accuracy did not improve from 0.07337

92/92 - 3s - 27ms/step - accuracy: 0.0262 - loss: 51.7966 - val_accuracy: 0.0109 - val_loss: 12.1887 - learning_rate: 0.0010

Epoch 4/18

Epoch 4: val_accuracy did not improve from 0.07337

92/92 - 3s - 28ms/step - accuracy: 0.0292 - loss: 46.7831 - val_accuracy: 0.0408 - val_loss: 10.2483 - learning_rate: 0.0010

Epoch 5/18

Epoch 5: val_accuracy did not improve from 0.07337

92/92 - 2s - 25ms/step - accuracy: 0.0282 - loss: 41.8901 - val_accuracy: 0.0190 - val_loss: 8.2560 - learning_rate: 0.0010

Epoch 6/18

Epoch 6: val_accuracy did not improve from 0.07337

92/92 - 3s - 28ms/step - accuracy: 0.0299 - loss: 38.3006 - val_accuracy: 0.0408 - val_loss: 10.7084 - learning_rate: 0.0010

Epoch 7/18

Epoch 7: val_accuracy did not improve from 0.07337

Epoch 7: ReduceLROnPlateau reducing learning rate to 0.0003000000142492354.

92/92 - 2s - 26ms/step - accuracy: 0.0279 - loss: 33.9018 - val_accuracy: 0.0163 - val_loss: 9.5401 - learning_rate: 0.0010

Epoch 7: early stopping

Restoring model weights from the end of the best epoch: 2.

Model: "fc_baseline"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 160, 160, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ resizing (Resizing)             │ (None, 64, 64, 3)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 12288)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │     1,572,992 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 37)             │         4,773 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,577,765 (6.02 MB)

 Trainable params: 1,577,765 (6.02 MB)

 Non-trainable params: 0 (0.00 B)

## 7 Experimento CNN propia base

Esta arquitectura introduce filtros locales y pooling, pero evita augmentation y regularización avanzada. Su resultado permite medir el salto respecto al modelo Fully Connected.

In [10]:
cnn_baseline_model = train_or_load("cnn_baseline", build_cnn_baseline)
cnn_baseline_model.summary()

Entrenando cnn_baseline con 114,533 parámetros
Epoch 1/30

Epoch 1: val_accuracy improved from None to 0.02446, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_baseline.keras

Epoch 1: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_baseline.keras

92/92 - 8s - 82ms/step - accuracy: 0.0238 - loss: 3.6128 - val_accuracy: 0.0245 - val_loss: 3.6129 - learning_rate: 0.0010

Epoch 2/30

Epoch 2: val_accuracy improved from 0.02446 to 0.04620, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_baseline.keras

Epoch 2: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_baseline.keras

92/92 - 7s - 75ms/step - accuracy: 0.0312 - loss: 3.6065 - val_accuracy: 0.0462 - val_loss: 3.5994 - learning_rate: 0.0010

Epoch 3/30

Epoch 3: val_accuracy did not improve from 0.04620

92/92 - 7s - 74ms/step - accuracy: 0.0340 - loss: 3.5908 - val_accuracy: 0.0353 - val_loss: 3.5865 - learning_rate: 0.0010

Epoch 4/30

Epoch 4: val_accuracy did not improve from 0.04620

92/92 - 7s - 74ms/step - accuracy: 0.0384 - loss: 3.5738 - val_accuracy: 0.0326 - val_loss: 3.5816 - learning_rate: 0.0010

Epoch 5/30

Epoch 5: val_accuracy did not improve from 0.04620

92/92 - 7s - 75ms/step - accuracy: 0.0394 - loss: 3.5661 - val_accuracy: 0.0326 - val_loss: 3.5734 - learning_rate: 0.0010

Epoch 6/30

Epoch 6: val_accuracy did not improve from 0.04620

92/92 - 7s - 74ms/step - accuracy: 0.0479 - loss: 3.5631 - val_accuracy: 0.0462 - val_loss: 3.5731 - learning_rate: 0.0010

Epoch 7/30

Epoch 7: val_accuracy improved from 0.04620 to 0.05163, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_baseline.keras

Epoch 7: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_baseline.keras

92/92 - 7s - 74ms/step - accuracy: 0.0530 - loss: 3.5326 - val_accuracy: 0.0516 - val_loss: 3.5411 - learning_rate: 0.0010

Epoch 8/30

Epoch 8: val_accuracy did not improve from 0.05163

92/92 - 7s - 74ms/step - accuracy: 0.0537 - loss: 3.5217 - val_accuracy: 0.0435 - val_loss: 3.5192 - learning_rate: 0.0010

Epoch 9/30

Epoch 9: val_accuracy improved from 0.05163 to 0.07609, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_baseline.keras

Epoch 9: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_baseline.keras

92/92 - 7s - 75ms/step - accuracy: 0.0605 - loss: 3.4885 - val_accuracy: 0.0761 - val_loss: 3.4924 - learning_rate: 0.0010

Epoch 10/30

Epoch 10: val_accuracy did not improve from 0.07609

92/92 - 7s - 74ms/step - accuracy: 0.0662 - loss: 3.4639 - val_accuracy: 0.0679 - val_loss: 3.5286 - learning_rate: 0.0010

Epoch 11/30

Epoch 11: val_accuracy improved from 0.07609 to 0.07880, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_baseline.keras

Epoch 11: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_baseline.keras

92/92 - 7s - 75ms/step - accuracy: 0.0798 - loss: 3.4562 - val_accuracy: 0.0788 - val_loss: 3.4642 - learning_rate: 0.0010

Epoch 12/30

Epoch 12: val_accuracy improved from 0.07880 to 0.09511, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_baseline.keras

Epoch 12: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_baseline.keras

92/92 - 7s - 75ms/step - accuracy: 0.0839 - loss: 3.4255 - val_accuracy: 0.0951 - val_loss: 3.4575 - learning_rate: 0.0010

Epoch 13/30

Epoch 13: val_accuracy did not improve from 0.09511

92/92 - 7s - 75ms/step - accuracy: 0.0836 - loss: 3.3915 - val_accuracy: 0.0951 - val_loss: 3.4996 - learning_rate: 0.0010

Epoch 14/30

Epoch 14: val_accuracy improved from 0.09511 to 0.11141, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_baseline.keras

Epoch 14: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_baseline.keras

92/92 - 7s - 77ms/step - accuracy: 0.0931 - loss: 3.4247 - val_accuracy: 0.1114 - val_loss: 3.4112 - learning_rate: 0.0010

Epoch 15/30

Epoch 15: val_accuracy did not improve from 0.11141

92/92 - 7s - 77ms/step - accuracy: 0.1026 - loss: 3.4136 - val_accuracy: 0.0842 - val_loss: 3.5235 - learning_rate: 0.0010

Epoch 16/30

Epoch 16: val_accuracy did not improve from 0.11141

92/92 - 7s - 79ms/step - accuracy: 0.1002 - loss: 3.3997 - val_accuracy: 0.1114 - val_loss: 3.5838 - learning_rate: 0.0010

Epoch 17/30

Epoch 17: val_accuracy did not improve from 0.11141

Epoch 17: ReduceLROnPlateau reducing learning rate to 0.0003000000142492354.

92/92 - 7s - 80ms/step - accuracy: 0.0985 - loss: 3.4987 - val_accuracy: 0.1005 - val_loss: 3.5321 - learning_rate: 0.0010

Epoch 18/30

Epoch 18: val_accuracy did not improve from 0.11141

92/92 - 8s - 83ms/step - accuracy: 0.1179 - loss: 3.2647 - val_accuracy: 0.1087 - val_loss: 3.4494 - learning_rate: 3.0000e-04

Epoch 19/30

Epoch 19: val_accuracy did not improve from 0.11141

92/92 - 8s - 83ms/step - accuracy: 0.1192 - loss: 3.2849 - val_accuracy: 0.0951 - val_loss: 3.5260 - learning_rate: 3.0000e-04

Epoch 20/30

Epoch 20: val_accuracy did not improve from 0.11141

Epoch 20: ReduceLROnPlateau reducing learning rate to 9.000000427477062e-05.

92/92 - 8s - 84ms/step - accuracy: 0.1172 - loss: 3.2985 - val_accuracy: 0.0951 - val_loss: 3.4648 - learning_rate: 3.0000e-04

Epoch 20: early stopping

Restoring model weights from the end of the best epoch: 14.

Model: "cnn_baseline"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 160, 160, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d (Conv2D)                 │ (None, 160, 160, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 80, 80, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 80, 80, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 40, 40, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 40, 40, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 20, 20, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d        │ (None, 128)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 37)             │         4,773 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 114,533 (447.39 KB)

 Trainable params: 114,533 (447.39 KB)

 Non-trainable params: 0 (0.00 B)

## 8 CNN propia regularizada sin Data augmentation

La red propuesta incorpora mayor profundidad, Batch Normalization, Spatial Dropout y Global Average Pooling. Esta primera variante no transforma imágenes y actúa como control de la ablación.

In [11]:
cnn_regularized_no_aug_model = train_or_load(
    "cnn_regularized_no_aug", lambda: build_regularized_cnn(use_augmentation=False)
)
cnn_regularized_no_aug_model.summary()

Entrenando cnn_regularized_no_aug con 1,251,205 parámetros
Epoch 1/35

Epoch 1: val_accuracy improved from None to 0.03533, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

Epoch 1: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

92/92 - 35s - 376ms/step - accuracy: 0.0374 - loss: 4.0239 - val_accuracy: 0.0353 - val_loss: 3.7421 - learning_rate: 7.0000e-04

Epoch 2/35

Epoch 2: val_accuracy did not improve from 0.03533

92/92 - 33s - 362ms/step - accuracy: 0.0479 - loss: 3.8312 - val_accuracy: 0.0217 - val_loss: 4.0468 - learning_rate: 7.0000e-04

Epoch 3/35

Epoch 3: val_accuracy did not improve from 0.03533

92/92 - 34s - 370ms/step - accuracy: 0.0496 - loss: 3.7450 - val_accuracy: 0.0190 - val_loss: 4.0889 - learning_rate: 7.0000e-04

Epoch 4/35

Epoch 4: val_accuracy did not improve from 0.03533

Epoch 4: ReduceLROnPlateau reducing learning rate to 0.0002099999925121665.

92/92 - 34s - 370ms/step - accuracy: 0.0530 - loss: 3.6797 - val_accuracy: 0.0217 - val_loss: 4.2518 - learning_rate: 7.0000e-04

Epoch 5/35

Epoch 5: val_accuracy did not improve from 0.03533

92/92 - 34s - 368ms/step - accuracy: 0.0543 - loss: 3.6233 - val_accuracy: 0.0245 - val_loss: 3.8193 - learning_rate: 2.1000e-04

Epoch 6/35

Epoch 6: val_accuracy improved from 0.03533 to 0.04620, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

Epoch 6: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

92/92 - 34s - 373ms/step - accuracy: 0.0588 - loss: 3.5996 - val_accuracy: 0.0462 - val_loss: 3.5971 - learning_rate: 2.1000e-04

Epoch 7/35

Epoch 7: val_accuracy improved from 0.04620 to 0.05163, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

Epoch 7: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

92/92 - 34s - 373ms/step - accuracy: 0.0730 - loss: 3.5252 - val_accuracy: 0.0516 - val_loss: 3.5772 - learning_rate: 2.1000e-04

Epoch 8/35

Epoch 8: val_accuracy improved from 0.05163 to 0.09511, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

Epoch 8: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

92/92 - 35s - 378ms/step - accuracy: 0.0747 - loss: 3.5137 - val_accuracy: 0.0951 - val_loss: 3.4076 - learning_rate: 2.1000e-04

Epoch 9/35

Epoch 9: val_accuracy did not improve from 0.09511

92/92 - 35s - 379ms/step - accuracy: 0.0788 - loss: 3.4984 - val_accuracy: 0.0788 - val_loss: 3.4302 - learning_rate: 2.1000e-04

Epoch 10/35

Epoch 10: val_accuracy improved from 0.09511 to 0.12772, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

Epoch 10: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

92/92 - 35s - 384ms/step - accuracy: 0.0863 - loss: 3.4619 - val_accuracy: 0.1277 - val_loss: 3.3966 - learning_rate: 2.1000e-04

Epoch 11/35

Epoch 11: val_accuracy did not improve from 0.12772

92/92 - 35s - 382ms/step - accuracy: 0.0788 - loss: 3.4647 - val_accuracy: 0.0897 - val_loss: 3.4079 - learning_rate: 2.1000e-04

Epoch 12/35

Epoch 12: val_accuracy did not improve from 0.12772

92/92 - 35s - 381ms/step - accuracy: 0.0927 - loss: 3.4130 - val_accuracy: 0.1141 - val_loss: 3.2964 - learning_rate: 2.1000e-04

Epoch 13/35

Epoch 13: val_accuracy did not improve from 0.12772

92/92 - 35s - 385ms/step - accuracy: 0.0971 - loss: 3.3812 - val_accuracy: 0.1114 - val_loss: 3.3509 - learning_rate: 2.1000e-04

Epoch 14/35

Epoch 14: val_accuracy did not improve from 0.12772

92/92 - 35s - 383ms/step - accuracy: 0.0995 - loss: 3.3535 - val_accuracy: 0.1277 - val_loss: 3.3449 - learning_rate: 2.1000e-04

Epoch 15/35

Epoch 15: val_accuracy did not improve from 0.12772

92/92 - 36s - 391ms/step - accuracy: 0.1012 - loss: 3.3404 - val_accuracy: 0.1141 - val_loss: 3.2871 - learning_rate: 2.1000e-04

Epoch 16/35

Epoch 16: val_accuracy did not improve from 0.12772

92/92 - 36s - 389ms/step - accuracy: 0.1101 - loss: 3.2903 - val_accuracy: 0.1141 - val_loss: 3.3186 - learning_rate: 2.1000e-04

Epoch 17/35

Epoch 17: val_accuracy improved from 0.12772 to 0.13315, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

Epoch 17: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

92/92 - 36s - 390ms/step - accuracy: 0.1145 - loss: 3.3068 - val_accuracy: 0.1332 - val_loss: 3.2534 - learning_rate: 2.1000e-04

Epoch 18/35

Epoch 18: val_accuracy improved from 0.13315 to 0.15217, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

Epoch 18: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

92/92 - 36s - 389ms/step - accuracy: 0.1138 - loss: 3.2653 - val_accuracy: 0.1522 - val_loss: 3.1411 - learning_rate: 2.1000e-04

Epoch 19/35

Epoch 19: val_accuracy did not improve from 0.15217

92/92 - 36s - 388ms/step - accuracy: 0.1199 - loss: 3.2576 - val_accuracy: 0.1495 - val_loss: 3.1177 - learning_rate: 2.1000e-04

Epoch 20/35

Epoch 20: val_accuracy did not improve from 0.15217

92/92 - 36s - 392ms/step - accuracy: 0.1345 - loss: 3.2124 - val_accuracy: 0.1413 - val_loss: 3.1090 - learning_rate: 2.1000e-04

Epoch 21/35

Epoch 21: val_accuracy did not improve from 0.15217

92/92 - 36s - 395ms/step - accuracy: 0.1342 - loss: 3.1458 - val_accuracy: 0.1522 - val_loss: 3.0912 - learning_rate: 2.1000e-04

Epoch 22/35

Epoch 22: val_accuracy did not improve from 0.15217

92/92 - 36s - 390ms/step - accuracy: 0.1389 - loss: 3.1494 - val_accuracy: 0.1467 - val_loss: 3.1158 - learning_rate: 2.1000e-04

Epoch 23/35

Epoch 23: val_accuracy did not improve from 0.15217

92/92 - 36s - 389ms/step - accuracy: 0.1498 - loss: 3.1068 - val_accuracy: 0.1413 - val_loss: 3.2293 - learning_rate: 2.1000e-04

Epoch 24/35

Epoch 24: val_accuracy improved from 0.15217 to 0.17120, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

Epoch 24: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

92/92 - 36s - 392ms/step - accuracy: 0.1542 - loss: 3.0713 - val_accuracy: 0.1712 - val_loss: 3.0361 - learning_rate: 2.1000e-04

Epoch 25/35

Epoch 25: val_accuracy did not improve from 0.17120

92/92 - 36s - 392ms/step - accuracy: 0.1722 - loss: 3.0386 - val_accuracy: 0.1386 - val_loss: 3.0664 - learning_rate: 2.1000e-04

Epoch 26/35

Epoch 26: val_accuracy improved from 0.17120 to 0.17663, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

Epoch 26: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

92/92 - 36s - 397ms/step - accuracy: 0.1654 - loss: 3.0294 - val_accuracy: 0.1766 - val_loss: 2.9728 - learning_rate: 2.1000e-04

Epoch 27/35

Epoch 27: val_accuracy improved from 0.17663 to 0.18750, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

Epoch 27: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

92/92 - 36s - 392ms/step - accuracy: 0.1726 - loss: 2.9978 - val_accuracy: 0.1875 - val_loss: 2.8907 - learning_rate: 2.1000e-04

Epoch 28/35

Epoch 28: val_accuracy did not improve from 0.18750

92/92 - 36s - 393ms/step - accuracy: 0.1766 - loss: 2.9637 - val_accuracy: 0.1440 - val_loss: 3.0595 - learning_rate: 2.1000e-04

Epoch 29/35

Epoch 29: val_accuracy did not improve from 0.18750

92/92 - 36s - 393ms/step - accuracy: 0.1800 - loss: 2.9553 - val_accuracy: 0.1603 - val_loss: 3.0033 - learning_rate: 2.1000e-04

Epoch 30/35

Epoch 30: val_accuracy improved from 0.18750 to 0.20380, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

Epoch 30: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

92/92 - 37s - 399ms/step - accuracy: 0.1882 - loss: 2.8992 - val_accuracy: 0.2038 - val_loss: 2.8668 - learning_rate: 2.1000e-04

Epoch 31/35

Epoch 31: val_accuracy improved from 0.20380 to 0.22826, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

Epoch 31: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

92/92 - 37s - 398ms/step - accuracy: 0.1868 - loss: 2.8814 - val_accuracy: 0.2283 - val_loss: 2.8044 - learning_rate: 2.1000e-04

Epoch 32/35

Epoch 32: val_accuracy did not improve from 0.22826

92/92 - 36s - 392ms/step - accuracy: 0.2007 - loss: 2.8608 - val_accuracy: 0.1902 - val_loss: 2.9142 - learning_rate: 2.1000e-04

Epoch 33/35

Epoch 33: val_accuracy did not improve from 0.22826

92/92 - 36s - 396ms/step - accuracy: 0.2038 - loss: 2.8506 - val_accuracy: 0.2092 - val_loss: 2.8407 - learning_rate: 2.1000e-04

Epoch 34/35

Epoch 34: val_accuracy did not improve from 0.22826

Epoch 34: ReduceLROnPlateau reducing learning rate to 6.299999949987978e-05.

92/92 - 37s - 399ms/step - accuracy: 0.2004 - loss: 2.8347 - val_accuracy: 0.1033 - val_loss: 3.3336 - learning_rate: 2.1000e-04

Epoch 35/35

Epoch 35: val_accuracy improved from 0.22826 to 0.24457, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

Epoch 35: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_no_aug.keras

92/92 - 37s - 398ms/step - accuracy: 0.2160 - loss: 2.7577 - val_accuracy: 0.2446 - val_loss: 2.6694 - learning_rate: 6.3000e-05

Restoring model weights from the end of the best epoch: 35.

Model: "cnn_regularized_no_aug"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 160, 160, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d (Conv2D)                 │ (None, 160, 160, 32)   │           864 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 160, 160, 32)   │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation (Activation)         │ (None, 160, 160, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 160, 160, 32)   │         9,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 160, 160, 32)   │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_1 (Activation)       │ (None, 160, 160, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 80, 80, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ spatial_dropout2d               │ (None, 80, 80, 32)     │             0 │
│ (SpatialDropout2D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 80, 80, 64)     │        18,432 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 80, 80, 64)     │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_2 (Activation)       │ (None, 80, 80, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 80, 80, 64)     │        36,864 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 80, 80, 64)     │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_3 (Activation)       │ (None, 80, 80, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 40, 40, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ spatial_dropout2d_1             │ (None, 40, 40, 64)     │             0 │
│ (SpatialDropout2D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 40, 40, 128)    │        73,728 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, 40, 40, 128)    │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_4 (Activation)       │ (None, 40, 40, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 40, 40, 128)    │       147,456 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_5           │ (None, 40, 40, 128)    │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_5 (Activation)       │ (None, 40, 40, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 20, 20, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ spatial_dropout2d_2             │ (None, 20, 20, 128)    │             0 │
│ (SpatialDropout2D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 20, 20, 256)    │       294,912 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_6           │ (None, 20, 20, 256)    │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_6 (Activation)       │ (None, 20, 20, 256)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 20, 20, 256)    │       589,824 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_7           │ (None, 20, 20, 256)    │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_7 (Activation)       │ (None, 20, 20, 256)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 10, 10, 256)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ spatial_dropout2d_3             │ (None, 10, 10, 256)    │             0 │
│ (SpatialDropout2D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d        │ (None, 256)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 256)            │        65,536 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_8           │ (None, 256)            │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_8 (Activation)       │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 37)             │         9,509 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,251,205 (4.77 MB)

 Trainable params: 1,248,773 (4.76 MB)

 Non-trainable params: 2,432 (9.50 KB)

## 9 CNN propia regularizada con Data augmentation

Se reutiliza exactamente la misma CNN y se activan flip horizontal, rotación, zoom, traslación y contraste moderados. No se usan flips verticales porque no representan una variación natural de las mascotas.

In [12]:
cnn_regularized_aug_model = train_or_load(
    "cnn_regularized_aug", lambda: build_regularized_cnn(use_augmentation=True)
)
cnn_regularized_aug_model.summary()

Entrenando cnn_regularized_aug con 1,251,205 parámetros
Epoch 1/40

Epoch 1: val_accuracy improved from None to 0.03804, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

Epoch 1: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

92/92 - 41s - 451ms/step - accuracy: 0.0370 - loss: 3.9964 - val_accuracy: 0.0380 - val_loss: 3.7657 - learning_rate: 7.0000e-04

Epoch 2/40

Epoch 2: val_accuracy did not improve from 0.03804

92/92 - 33s - 355ms/step - accuracy: 0.0442 - loss: 3.8060 - val_accuracy: 0.0380 - val_loss: 4.0638 - learning_rate: 7.0000e-04

Epoch 3/40

Epoch 3: val_accuracy did not improve from 0.03804

92/92 - 35s - 379ms/step - accuracy: 0.0489 - loss: 3.7484 - val_accuracy: 0.0272 - val_loss: 3.8604 - learning_rate: 7.0000e-04

Epoch 4/40

Epoch 4: val_accuracy improved from 0.03804 to 0.04348, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

Epoch 4: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

92/92 - 41s - 444ms/step - accuracy: 0.0462 - loss: 3.7229 - val_accuracy: 0.0435 - val_loss: 3.8334 - learning_rate: 7.0000e-04

Epoch 5/40

Epoch 5: val_accuracy improved from 0.04348 to 0.04891, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

Epoch 5: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

Epoch 5: ReduceLROnPlateau reducing learning rate to 0.0002099999925121665.

92/92 - 39s - 426ms/step - accuracy: 0.0547 - loss: 3.6846 - val_accuracy: 0.0489 - val_loss: 3.8159 - learning_rate: 7.0000e-04

Epoch 6/40

Epoch 6: val_accuracy improved from 0.04891 to 0.06522, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

Epoch 6: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

92/92 - 39s - 426ms/step - accuracy: 0.0652 - loss: 3.5953 - val_accuracy: 0.0652 - val_loss: 3.5009 - learning_rate: 2.1000e-04

Epoch 7/40

Epoch 7: val_accuracy improved from 0.06522 to 0.07337, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

Epoch 7: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

92/92 - 39s - 424ms/step - accuracy: 0.0832 - loss: 3.5495 - val_accuracy: 0.0734 - val_loss: 3.4831 - learning_rate: 2.1000e-04

Epoch 8/40

Epoch 8: val_accuracy did not improve from 0.07337

92/92 - 40s - 431ms/step - accuracy: 0.0730 - loss: 3.5208 - val_accuracy: 0.0734 - val_loss: 3.4720 - learning_rate: 2.1000e-04

Epoch 9/40

Epoch 9: val_accuracy improved from 0.07337 to 0.07609, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

Epoch 9: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

92/92 - 39s - 429ms/step - accuracy: 0.0771 - loss: 3.4850 - val_accuracy: 0.0761 - val_loss: 3.4967 - learning_rate: 2.1000e-04

Epoch 10/40

Epoch 10: val_accuracy did not improve from 0.07609

92/92 - 39s - 425ms/step - accuracy: 0.0907 - loss: 3.4867 - val_accuracy: 0.0734 - val_loss: 3.4601 - learning_rate: 2.1000e-04

Epoch 11/40

Epoch 11: val_accuracy did not improve from 0.07609

92/92 - 39s - 425ms/step - accuracy: 0.0724 - loss: 3.4806 - val_accuracy: 0.0652 - val_loss: 3.6150 - learning_rate: 2.1000e-04

Epoch 12/40

Epoch 12: val_accuracy improved from 0.07609 to 0.11141, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

Epoch 12: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

92/92 - 39s - 423ms/step - accuracy: 0.0924 - loss: 3.4401 - val_accuracy: 0.1114 - val_loss: 3.4165 - learning_rate: 2.1000e-04

Epoch 13/40

Epoch 13: val_accuracy did not improve from 0.11141

92/92 - 38s - 415ms/step - accuracy: 0.0934 - loss: 3.4133 - val_accuracy: 0.1005 - val_loss: 3.4639 - learning_rate: 2.1000e-04

Epoch 14/40

Epoch 14: val_accuracy did not improve from 0.11141

92/92 - 40s - 432ms/step - accuracy: 0.0965 - loss: 3.3944 - val_accuracy: 0.0598 - val_loss: 3.8819 - learning_rate: 2.1000e-04

Epoch 15/40

Epoch 15: val_accuracy did not improve from 0.11141

92/92 - 50s - 543ms/step - accuracy: 0.1012 - loss: 3.3642 - val_accuracy: 0.0924 - val_loss: 3.4292 - learning_rate: 2.1000e-04

Epoch 16/40

Epoch 16: val_accuracy improved from 0.11141 to 0.11957, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

Epoch 16: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

92/92 - 49s - 535ms/step - accuracy: 0.1046 - loss: 3.3285 - val_accuracy: 0.1196 - val_loss: 3.3045 - learning_rate: 2.1000e-04

Epoch 17/40

Epoch 17: val_accuracy did not improve from 0.11957

92/92 - 45s - 489ms/step - accuracy: 0.1050 - loss: 3.2926 - val_accuracy: 0.1033 - val_loss: 3.2836 - learning_rate: 2.1000e-04

Epoch 18/40

Epoch 18: val_accuracy did not improve from 0.11957

92/92 - 44s - 483ms/step - accuracy: 0.1135 - loss: 3.3233 - val_accuracy: 0.0734 - val_loss: 3.6760 - learning_rate: 2.1000e-04

Epoch 19/40

Epoch 19: val_accuracy did not improve from 0.11957

92/92 - 44s - 474ms/step - accuracy: 0.1087 - loss: 3.2950 - val_accuracy: 0.1168 - val_loss: 3.3302 - learning_rate: 2.1000e-04

Epoch 20/40

Epoch 20: val_accuracy did not improve from 0.11957

92/92 - 43s - 468ms/step - accuracy: 0.1206 - loss: 3.2587 - val_accuracy: 0.0679 - val_loss: 3.4660 - learning_rate: 2.1000e-04

Epoch 21/40

Epoch 21: val_accuracy did not improve from 0.11957

Epoch 21: ReduceLROnPlateau reducing learning rate to 6.299999949987978e-05.

92/92 - 42s - 460ms/step - accuracy: 0.1199 - loss: 3.2550 - val_accuracy: 0.0951 - val_loss: 3.4877 - learning_rate: 2.1000e-04

Epoch 22/40

Epoch 22: val_accuracy improved from 0.11957 to 0.12500, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

Epoch 22: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

92/92 - 44s - 477ms/step - accuracy: 0.1281 - loss: 3.1912 - val_accuracy: 0.1250 - val_loss: 3.2213 - learning_rate: 6.3000e-05

Epoch 23/40

Epoch 23: val_accuracy did not improve from 0.12500

92/92 - 44s - 475ms/step - accuracy: 0.1216 - loss: 3.2031 - val_accuracy: 0.1114 - val_loss: 3.2388 - learning_rate: 6.3000e-05

Epoch 24/40

Epoch 24: val_accuracy improved from 0.12500 to 0.12772, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

Epoch 24: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

92/92 - 46s - 498ms/step - accuracy: 0.1389 - loss: 3.1776 - val_accuracy: 0.1277 - val_loss: 3.1535 - learning_rate: 6.3000e-05

Epoch 25/40

Epoch 25: val_accuracy did not improve from 0.12772

92/92 - 43s - 472ms/step - accuracy: 0.1287 - loss: 3.1654 - val_accuracy: 0.1087 - val_loss: 3.2368 - learning_rate: 6.3000e-05

Epoch 26/40

Epoch 26: val_accuracy did not improve from 0.12772

92/92 - 43s - 466ms/step - accuracy: 0.1382 - loss: 3.1333 - val_accuracy: 0.1168 - val_loss: 3.2905 - learning_rate: 6.3000e-05

Epoch 27/40

Epoch 27: val_accuracy did not improve from 0.12772

92/92 - 46s - 497ms/step - accuracy: 0.1325 - loss: 3.1209 - val_accuracy: 0.1250 - val_loss: 3.1566 - learning_rate: 6.3000e-05

Epoch 28/40

Epoch 28: val_accuracy improved from 0.12772 to 0.16304, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

Epoch 28: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

92/92 - 46s - 497ms/step - accuracy: 0.1488 - loss: 3.1194 - val_accuracy: 0.1630 - val_loss: 3.1008 - learning_rate: 6.3000e-05

Epoch 29/40

Epoch 29: val_accuracy did not improve from 0.16304

92/92 - 44s - 474ms/step - accuracy: 0.1389 - loss: 3.1431 - val_accuracy: 0.1359 - val_loss: 3.1161 - learning_rate: 6.3000e-05

Epoch 30/40

Epoch 30: val_accuracy did not improve from 0.16304

92/92 - 45s - 489ms/step - accuracy: 0.1427 - loss: 3.1169 - val_accuracy: 0.1277 - val_loss: 3.2077 - learning_rate: 6.3000e-05

Epoch 31/40

Epoch 31: val_accuracy did not improve from 0.16304

92/92 - 43s - 470ms/step - accuracy: 0.1444 - loss: 3.0902 - val_accuracy: 0.1386 - val_loss: 3.1327 - learning_rate: 6.3000e-05

Epoch 32/40

Epoch 32: val_accuracy improved from 0.16304 to 0.16576, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

Epoch 32: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

92/92 - 41s - 451ms/step - accuracy: 0.1478 - loss: 3.0972 - val_accuracy: 0.1658 - val_loss: 3.0343 - learning_rate: 6.3000e-05

Epoch 33/40

Epoch 33: val_accuracy improved from 0.16576 to 0.17120, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

Epoch 33: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

92/92 - 41s - 441ms/step - accuracy: 0.1450 - loss: 3.0833 - val_accuracy: 0.1712 - val_loss: 3.0594 - learning_rate: 6.3000e-05

Epoch 34/40

Epoch 34: val_accuracy did not improve from 0.17120

92/92 - 40s - 438ms/step - accuracy: 0.1603 - loss: 3.0647 - val_accuracy: 0.1630 - val_loss: 3.0002 - learning_rate: 6.3000e-05

Epoch 35/40

Epoch 35: val_accuracy did not improve from 0.17120

92/92 - 40s - 432ms/step - accuracy: 0.1495 - loss: 3.0460 - val_accuracy: 0.1250 - val_loss: 3.0686 - learning_rate: 6.3000e-05

Epoch 36/40

Epoch 36: val_accuracy did not improve from 0.17120

92/92 - 40s - 433ms/step - accuracy: 0.1549 - loss: 3.0349 - val_accuracy: 0.1522 - val_loss: 3.0808 - learning_rate: 6.3000e-05

Epoch 37/40

Epoch 37: val_accuracy did not improve from 0.17120

92/92 - 40s - 435ms/step - accuracy: 0.1658 - loss: 3.0334 - val_accuracy: 0.1467 - val_loss: 3.0286 - learning_rate: 6.3000e-05

Epoch 38/40

Epoch 38: val_accuracy did not improve from 0.17120

Epoch 38: ReduceLROnPlateau reducing learning rate to 1.889999984996393e-05.

92/92 - 40s - 433ms/step - accuracy: 0.1542 - loss: 3.0337 - val_accuracy: 0.1549 - val_loss: 3.0103 - learning_rate: 6.3000e-05

Epoch 39/40

Epoch 39: val_accuracy improved from 0.17120 to 0.17391, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

Epoch 39: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/cnn_regularized_aug.keras

92/92 - 40s - 432ms/step - accuracy: 0.1641 - loss: 3.0141 - val_accuracy: 0.1739 - val_loss: 2.9760 - learning_rate: 1.8900e-05

Epoch 40/40

Epoch 40: val_accuracy did not improve from 0.17391

92/92 - 40s - 440ms/step - accuracy: 0.1709 - loss: 3.0136 - val_accuracy: 0.1739 - val_loss: 3.0019 - learning_rate: 1.8900e-05

Restoring model weights from the end of the best epoch: 39.

Model: "cnn_regularized_aug"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 160, 160, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ data_augmentation (Sequential)  │ (None, 160, 160, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d (Conv2D)                 │ (None, 160, 160, 32)   │           864 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 160, 160, 32)   │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation (Activation)         │ (None, 160, 160, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 160, 160, 32)   │         9,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 160, 160, 32)   │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_1 (Activation)       │ (None, 160, 160, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 80, 80, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ spatial_dropout2d               │ (None, 80, 80, 32)     │             0 │
│ (SpatialDropout2D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 80, 80, 64)     │        18,432 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 80, 80, 64)     │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_2 (Activation)       │ (None, 80, 80, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 80, 80, 64)     │        36,864 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 80, 80, 64)     │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_3 (Activation)       │ (None, 80, 80, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 40, 40, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ spatial_dropout2d_1             │ (None, 40, 40, 64)     │             0 │
│ (SpatialDropout2D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 40, 40, 128)    │        73,728 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, 40, 40, 128)    │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_4 (Activation)       │ (None, 40, 40, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 40, 40, 128)    │       147,456 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_5           │ (None, 40, 40, 128)    │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_5 (Activation)       │ (None, 40, 40, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 20, 20, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ spatial_dropout2d_2             │ (None, 20, 20, 128)    │             0 │
│ (SpatialDropout2D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 20, 20, 256)    │       294,912 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_6           │ (None, 20, 20, 256)    │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_6 (Activation)       │ (None, 20, 20, 256)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 20, 20, 256)    │       589,824 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_7           │ (None, 20, 20, 256)    │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_7 (Activation)       │ (None, 20, 20, 256)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 10, 10, 256)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ spatial_dropout2d_3             │ (None, 10, 10, 256)    │             0 │
│ (SpatialDropout2D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d        │ (None, 256)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 256)            │        65,536 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_8           │ (None, 256)            │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_8 (Activation)       │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 37)             │         9,509 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,251,205 (4.77 MB)

 Trainable params: 1,248,773 (4.76 MB)

 Non-trainable params: 2,432 (9.50 KB)

## 10 Transfer learning con MobileNetV2

MobileNetV2 aporta representaciones aprendidas en ImageNet. En esta fase el backbone permanece congelado y solo se entrena la cabeza multiclase. Esto reduce el riesgo de destruir características útiles con un dataset relativamente pequeño.

In [13]:
mobilenet_transfer_model = train_or_load("mobilenet_transfer", build_mobilenet_transfer)
mobilenet_transfer_model.summary()

Entrenando mobilenet_transfer con 2,305,381 parámetros
Epoch 1/20

Epoch 1: val_accuracy improved from None to 0.80978, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/mobilenet_transfer.keras

Epoch 1: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/mobilenet_transfer.keras

92/92 - 15s - 168ms/step - accuracy: 0.4450 - loss: 2.0898 - val_accuracy: 0.8098 - val_loss: 0.7312 - learning_rate: 0.0010

Epoch 2/20

Epoch 2: val_accuracy improved from 0.80978 to 0.85054, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/mobilenet_transfer.keras

Epoch 2: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/mobilenet_transfer.keras

92/92 - 12s - 128ms/step - accuracy: 0.7252 - loss: 0.8805 - val_accuracy: 0.8505 - val_loss: 0.5121 - learning_rate: 0.0010

Epoch 3/20

Epoch 3: val_accuracy improved from 0.85054 to 0.86141, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/mobilenet_transfer.keras

Epoch 3: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/mobilenet_transfer.keras

92/92 - 12s - 132ms/step - accuracy: 0.7945 - loss: 0.6520 - val_accuracy: 0.8614 - val_loss: 0.4459 - learning_rate: 0.0010

Epoch 4/20

Epoch 4: val_accuracy improved from 0.86141 to 0.86957, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/mobilenet_transfer.keras

Epoch 4: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/mobilenet_transfer.keras

92/92 - 12s - 130ms/step - accuracy: 0.8200 - loss: 0.5783 - val_accuracy: 0.8696 - val_loss: 0.4112 - learning_rate: 0.0010

Epoch 5/20

Epoch 5: val_accuracy improved from 0.86957 to 0.87228, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/mobilenet_transfer.keras

Epoch 5: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/mobilenet_transfer.keras

92/92 - 11s - 119ms/step - accuracy: 0.8417 - loss: 0.4801 - val_accuracy: 0.8723 - val_loss: 0.3838 - learning_rate: 0.0010

Epoch 6/20

Epoch 6: val_accuracy did not improve from 0.87228

92/92 - 12s - 126ms/step - accuracy: 0.8458 - loss: 0.4580 - val_accuracy: 0.8723 - val_loss: 0.4153 - learning_rate: 0.0010

Epoch 7/20

Epoch 7: val_accuracy improved from 0.87228 to 0.87500, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/mobilenet_transfer.keras

Epoch 7: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/mobilenet_transfer.keras

Epoch 7: ReduceLROnPlateau reducing learning rate to 0.0003000000142492354.

92/92 - 12s - 134ms/step - accuracy: 0.8764 - loss: 0.3763 - val_accuracy: 0.8750 - val_loss: 0.4036 - learning_rate: 0.0010

Epoch 8/20

Epoch 8: val_accuracy did not improve from 0.87500

92/92 - 11s - 119ms/step - accuracy: 0.8913 - loss: 0.3536 - val_accuracy: 0.8641 - val_loss: 0.3828 - learning_rate: 3.0000e-04

Epoch 9/20

Epoch 9: val_accuracy did not improve from 0.87500

92/92 - 9s - 101ms/step - accuracy: 0.8933 - loss: 0.3401 - val_accuracy: 0.8614 - val_loss: 0.3879 - learning_rate: 3.0000e-04

Epoch 10/20

Epoch 10: val_accuracy did not improve from 0.87500

92/92 - 9s - 94ms/step - accuracy: 0.8937 - loss: 0.3341 - val_accuracy: 0.8750 - val_loss: 0.3736 - learning_rate: 3.0000e-04

Epoch 11/20

Epoch 11: val_accuracy did not improve from 0.87500

92/92 - 9s - 93ms/step - accuracy: 0.8923 - loss: 0.3216 - val_accuracy: 0.8696 - val_loss: 0.3735 - learning_rate: 3.0000e-04

Epoch 12/20

Epoch 12: val_accuracy improved from 0.87500 to 0.87772, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/mobilenet_transfer.keras

Epoch 12: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/mobilenet_transfer.keras

Epoch 12: ReduceLROnPlateau reducing learning rate to 9.000000427477062e-05.

92/92 - 9s - 99ms/step - accuracy: 0.8991 - loss: 0.3191 - val_accuracy: 0.8777 - val_loss: 0.3743 - learning_rate: 3.0000e-04

Epoch 13/20

Epoch 13: val_accuracy did not improve from 0.87772

92/92 - 9s - 94ms/step - accuracy: 0.9073 - loss: 0.3071 - val_accuracy: 0.8723 - val_loss: 0.3722 - learning_rate: 9.0000e-05

Epoch 14/20

Epoch 14: val_accuracy did not improve from 0.87772

92/92 - 9s - 94ms/step - accuracy: 0.9144 - loss: 0.2743 - val_accuracy: 0.8723 - val_loss: 0.3715 - learning_rate: 9.0000e-05

Epoch 15/20

Epoch 15: val_accuracy did not improve from 0.87772

92/92 - 9s - 96ms/step - accuracy: 0.9124 - loss: 0.2804 - val_accuracy: 0.8723 - val_loss: 0.3716 - learning_rate: 9.0000e-05

Epoch 16/20

Epoch 16: val_accuracy did not improve from 0.87772

92/92 - 9s - 99ms/step - accuracy: 0.9093 - loss: 0.2942 - val_accuracy: 0.8750 - val_loss: 0.3678 - learning_rate: 9.0000e-05

Epoch 17/20

Epoch 17: val_accuracy did not improve from 0.87772

92/92 - 9s - 96ms/step - accuracy: 0.9164 - loss: 0.2681 - val_accuracy: 0.8750 - val_loss: 0.3651 - learning_rate: 9.0000e-05

Epoch 17: early stopping

Restoring model weights from the end of the best epoch: 12.

Model: "mobilenet_transfer"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 160, 160, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ data_augmentation (Sequential)  │ (None, 160, 160, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ mobilenet_normalization         │ (None, 160, 160, 3)    │             0 │
│ (Rescaling)                     │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ mobilenetv2_1.00_160            │ (None, 5, 5, 1280)     │     2,257,984 │
│ (Functional)                    │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d        │ (None, 1280)           │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 1280)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 37)             │        47,397 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,305,381 (8.79 MB)

 Trainable params: 47,397 (185.14 KB)

 Non-trainable params: 2,257,984 (8.61 MB)

## 11 Fine tuning parcial

El fine tuning parte del **mejor checkpoint** de transfer learning. Se descongelan solo las últimas 30 capas del backbone, se mantienen congeladas las capas Batch Normalization y se reduce el learning rate a `1e-5`. De este modo se adapta la representación a las razas sin modificar agresivamente los pesos preentrenados.

In [14]:
def prepare_finetuned_model():
    transfer_path = experiment_paths("mobilenet_transfer")["model"]
    if not transfer_path.exists():
        raise FileNotFoundError("Primero debe existir el checkpoint de mobilenet_transfer")
    model = keras.models.load_model(transfer_path, compile=False)
    backbone = next(
        layer for layer in model.layers
        if isinstance(layer, keras.Model) and "mobilenet" in layer.name.lower()
    )
    backbone.trainable = True
    for layer in backbone.layers[:-30]:
        layer.trainable = False
    for layer in backbone.layers[-30:]:
        if isinstance(layer, layers.BatchNormalization):
            layer.trainable = False
    model._name = "mobilenet_finetuned"
    return model

mobilenet_finetuned_model = train_or_load("mobilenet_finetuned", prepare_finetuned_model)
mobilenet_finetuned_model.summary()

Entrenando mobilenet_finetuned con 2,305,381 parámetros
Epoch 1/20

Epoch 1: val_accuracy improved from None to 0.86141, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/mobilenet_finetuned.keras

Epoch 1: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/mobilenet_finetuned.keras

92/92 - 14s - 148ms/step - accuracy: 0.9015 - loss: 0.3039 - val_accuracy: 0.8614 - val_loss: 0.3755 - learning_rate: 1.0000e-05

Epoch 2/20

Epoch 2: val_accuracy improved from 0.86141 to 0.88043, saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/mobilenet_finetuned.keras

Epoch 2: finished saving model to /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/models/mobilenet_finetuned.keras

92/92 - 10s - 112ms/step - accuracy: 0.9103 - loss: 0.2693 - val_accuracy: 0.8804 - val_loss: 0.3614 - learning_rate: 1.0000e-05

Epoch 3/20

Epoch 3: val_accuracy did not improve from 0.88043

92/92 - 10s - 105ms/step - accuracy: 0.9154 - loss: 0.2594 - val_accuracy: 0.8696 - val_loss: 0.3679 - learning_rate: 1.0000e-05

Epoch 4/20

Epoch 4: val_accuracy did not improve from 0.88043

92/92 - 10s - 108ms/step - accuracy: 0.9175 - loss: 0.2679 - val_accuracy: 0.8723 - val_loss: 0.3656 - learning_rate: 1.0000e-05

Epoch 5/20

Epoch 5: val_accuracy did not improve from 0.88043

Epoch 5: ReduceLROnPlateau reducing learning rate to 2.9999999242136253e-06.

92/92 - 10s - 108ms/step - accuracy: 0.9192 - loss: 0.2311 - val_accuracy: 0.8723 - val_loss: 0.3828 - learning_rate: 1.0000e-05

Epoch 6/20

Epoch 6: val_accuracy did not improve from 0.88043

92/92 - 10s - 106ms/step - accuracy: 0.9280 - loss: 0.2196 - val_accuracy: 0.8696 - val_loss: 0.3717 - learning_rate: 3.0000e-06

Epoch 7/20

Epoch 7: val_accuracy did not improve from 0.88043

92/92 - 10s - 107ms/step - accuracy: 0.9290 - loss: 0.2032 - val_accuracy: 0.8696 - val_loss: 0.3828 - learning_rate: 3.0000e-06

Epoch 8/20

Epoch 8: val_accuracy did not improve from 0.88043

Epoch 8: ReduceLROnPlateau reducing learning rate to 8.999999636216671e-07.

92/92 - 10s - 108ms/step - accuracy: 0.9243 - loss: 0.2135 - val_accuracy: 0.8723 - val_loss: 0.3761 - learning_rate: 3.0000e-06

Epoch 8: early stopping

Restoring model weights from the end of the best epoch: 2.

Model: "mobilenet_transfer"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 160, 160, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ data_augmentation (Sequential)  │ (None, 160, 160, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ mobilenet_normalization         │ (None, 160, 160, 3)    │             0 │
│ (Rescaling)                     │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ mobilenetv2_1.00_160            │ (None, 5, 5, 1280)     │     2,257,984 │
│ (Functional)                    │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d        │ (None, 1280)           │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 1280)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 37)             │        47,397 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,305,381 (8.79 MB)

 Trainable params: 1,558,117 (5.94 MB)

 Non-trainable params: 747,264 (2.85 MB)

## 12 Curvas y selección con validation

La selección ocurre antes de cualquier evaluación en test. Se comparan los checkpoints mediante validation y se diagnostica la brecha entre train y validation en la época de mejor `val_accuracy`.

In [15]:
def history_diagnostics(history):
    if not history or "val_accuracy" not in history:
        return {"best_epoch": np.nan, "train_accuracy": np.nan, "val_accuracy": np.nan,
                "generalization_gap": np.nan, "diagnosis": "historial no disponible"}
    best_index = int(np.argmax(history["val_accuracy"]))
    train_acc = float(history["accuracy"][best_index])
    val_acc = float(history["val_accuracy"][best_index])
    gap = train_acc - val_acc
    if val_acc < 0.50:
        diagnosis = "posible underfitting"
    elif gap > 0.10:
        diagnosis = "posible overfitting"
    else:
        diagnosis = "sin evidencia fuerte en las curvas"
    return {
        "best_epoch": best_index + 1,
        "train_accuracy": train_acc,
        "val_accuracy": val_acc,
        "generalization_gap": gap,
        "diagnosis": diagnosis,
    }

validation_rows = []
for name, model in models.items():
    val_loss, val_accuracy = model.evaluate(val_batches, verbose=0)
    diagnostics = history_diagnostics(histories[name])
    validation_rows.append({
        "model": name,
        "parameters": model.count_params(),
        "best_epoch": diagnostics["best_epoch"],
        "train_accuracy_at_best": diagnostics["train_accuracy"],
        "val_accuracy_history": diagnostics["val_accuracy"],
        "val_accuracy_checkpoint": float(val_accuracy),
        "generalization_gap": diagnostics["generalization_gap"],
        "curve_diagnosis": diagnostics["diagnosis"],
        "training_seconds": durations[name],
    })

validation_results = pd.DataFrame(validation_rows).sort_values(
    "val_accuracy_checkpoint", ascending=False
).reset_index(drop=True)
validation_results.to_csv(ARTIFACT_DIR / "validation_model_comparison.csv", index=False)
display(validation_results.style.format({
    "train_accuracy_at_best": "{:.3f}", "val_accuracy_history": "{:.3f}",
    "val_accuracy_checkpoint": "{:.3f}", "generalization_gap": "{:.3f}",
    "training_seconds": "{:.1f}"
}))

best_validation_model = validation_results.iloc[0]["model"]
print("Modelo seleccionado exclusivamente con validation:", best_validation_model)

Modelo seleccionado exclusivamente con validation: mobilenet_finetuned

In [16]:
def plot_histories(histories_to_plot, filename):
    available = {name: h for name, h in histories_to_plot.items() if h and "accuracy" in h}
    if not available:
        print("No hay historiales guardados para graficar.")
        return
    fig, axes = plt.subplots(1, 2, figsize=(15, 5))
    for name, history in available.items():
        epochs = np.arange(1, len(history["accuracy"]) + 1)
        axes[0].plot(epochs, history["accuracy"], alpha=0.75, label=f"{name} train")
        axes[0].plot(epochs, history["val_accuracy"], linestyle="--", label=f"{name} val")
        axes[1].plot(epochs, history["loss"], alpha=0.75, label=f"{name} train")
        axes[1].plot(epochs, history["val_loss"], linestyle="--", label=f"{name} val")
    axes[0].set(title="Accuracy por época", xlabel="Época", ylabel="Accuracy")
    axes[1].set(title="Loss por época", xlabel="Época", ylabel="Loss")
    for ax in axes:
        ax.legend(fontsize=7)
        ax.grid(alpha=0.25)
    plt.tight_layout()
    fig.savefig(ARTIFACT_DIR / filename, dpi=170, bbox_inches="tight")
    plt.show()

plot_histories(histories, "all_training_curves.png")
plot_histories(
    {best_validation_model: histories[best_validation_model]},
    "best_model_training_curves.png",
)

## 13 Evaluación final en test

A partir de este punto el diseño y la selección están cerrados. Test se abre una sola vez para obtener la comparación final. Sus métricas no deben utilizarse para volver atrás y cambiar hiperparámetros.

In [17]:
# FINAL TEST GATE: no mover esta evaluación antes de best_validation_model.
y_true = np.concatenate([labels.numpy() for _, labels in test_batches])
test_probabilities = {}
test_rows = []

for name, model in models.items():
    probabilities = model.predict(test_batches, verbose=0)
    predictions = probabilities.argmax(axis=1)
    report = classification_report(
        y_true,
        predictions,
        labels=np.arange(NUM_CLASSES),
        target_names=CLASS_NAMES,
        output_dict=True,
        zero_division=0,
    )
    loss, accuracy = model.evaluate(test_batches, verbose=0)
    test_probabilities[name] = probabilities
    test_rows.append({
        "model": name,
        "selected_by_validation": name == best_validation_model,
        "test_loss": float(loss),
        "test_accuracy": float(accuracy),
        "macro_precision": float(report["macro avg"]["precision"]),
        "macro_recall": float(report["macro avg"]["recall"]),
        "macro_f1": float(report["macro avg"]["f1-score"]),
        "weighted_f1": float(report["weighted avg"]["f1-score"]),
    })

test_results = pd.DataFrame(test_rows).sort_values("test_accuracy", ascending=False).reset_index(drop=True)
test_results.to_csv(ARTIFACT_DIR / "final_test_model_comparison.csv", index=False)
display(test_results.style.format({
    "test_loss": "{:.4f}", "test_accuracy": "{:.3%}", "macro_precision": "{:.3%}",
    "macro_recall": "{:.3%}", "macro_f1": "{:.3%}", "weighted_f1": "{:.3%}"
}))

selected_test_row = test_results[test_results["model"] == best_validation_model].iloc[0]
print(f"Accuracy final del modelo seleccionado: {selected_test_row['test_accuracy']:.2%}")
print("Objetivo de 85%:", "CUMPLIDO" if selected_test_row["test_accuracy"] >= 0.85 else "NO CUMPLIDO")

2026-09-11 23:47:33.986373: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence

Accuracy final del modelo seleccionado: 86.14%
Objetivo de 85%: CUMPLIDO

In [18]:
fig, ax = plt.subplots(figsize=(11, 5))
order = test_results.sort_values("test_accuracy")
colors = ["#16a34a" if selected else "#64748b" for selected in order["selected_by_validation"]]
ax.barh(order["model"], order["test_accuracy"], color=colors)
ax.axvline(0.85, color="#dc2626", linestyle="--", label="Objetivo 85%")
ax.set(xlabel="Test accuracy", title="Comparación final sin selección sobre test", xlim=(0, 1))
ax.legend()
for index, value in enumerate(order["test_accuracy"]):
    ax.text(min(value + 0.01, 0.96), index, f"{value:.1%}", va="center")
plt.tight_layout()
fig.savefig(ARTIFACT_DIR / "final_test_accuracy.png", dpi=170, bbox_inches="tight")
plt.show()

## 14 Precision recall y matriz de confusión

El análisis detallado se realiza sobre el modelo elegido por validation, incluso si otro modelo obtiene accidentalmente mejor test. Esto conserva la independencia metodológica del conjunto final.

In [19]:
selected_probabilities = test_probabilities[best_validation_model]
selected_predictions = selected_probabilities.argmax(axis=1)
selected_report_dict = classification_report(
    y_true,
    selected_predictions,
    labels=np.arange(NUM_CLASSES),
    target_names=CLASS_NAMES,
    output_dict=True,
    zero_division=0,
)
per_class_report = pd.DataFrame(selected_report_dict).T.loc[CLASS_NAMES]
per_class_report.index.name = "class_name"
per_class_report = per_class_report.sort_values("f1-score")
per_class_report.to_csv(ARTIFACT_DIR / "selected_model_per_class_metrics.csv")

print("Diez clases con menor F1")
display(per_class_report.head(10).style.format("{:.3f}"))
print("Diez clases con mayor F1")
display(per_class_report.tail(10).sort_values("f1-score", ascending=False).style.format("{:.3f}"))

Diez clases con menor F1

Diez clases con mayor F1

In [20]:
cm = confusion_matrix(y_true, selected_predictions, labels=np.arange(NUM_CLASSES))
cm_normalized = cm / np.maximum(cm.sum(axis=1, keepdims=True), 1)
np.save(ARTIFACT_DIR / "selected_model_confusion_matrix.npy", cm)

fig, ax = plt.subplots(figsize=(18, 15))
sns.heatmap(
    cm_normalized,
    cmap="Blues",
    xticklabels=CLASS_NAMES,
    yticklabels=CLASS_NAMES,
    vmin=0,
    vmax=1,
    square=True,
    cbar_kws={"label": "Proporción por clase real"},
    ax=ax,
)
ax.set(title=f"Matriz de confusión normalizada — {best_validation_model}",
       xlabel="Clase predicha", ylabel="Clase real")
plt.xticks(rotation=90, fontsize=8)
plt.yticks(rotation=0, fontsize=8)
plt.tight_layout()
fig.savefig(ARTIFACT_DIR / "selected_model_confusion_matrix.png", dpi=180, bbox_inches="tight")
plt.show()

In [21]:
confusion_rows = []
for true_id in range(NUM_CLASSES):
    for predicted_id in range(NUM_CLASSES):
        if true_id != predicted_id and cm[true_id, predicted_id] > 0:
            confusion_rows.append({
                "real": CLASS_NAMES[true_id],
                "predicted": CLASS_NAMES[predicted_id],
                "errors": int(cm[true_id, predicted_id]),
                "rate_within_real_class": float(cm_normalized[true_id, predicted_id]),
            })
confusion_pairs = pd.DataFrame(confusion_rows).sort_values(
    ["errors", "rate_within_real_class"], ascending=False
).reset_index(drop=True)
confusion_pairs.to_csv(ARTIFACT_DIR / "selected_model_confusion_pairs.csv", index=False)
print("Pares de confusión más frecuentes")
display(confusion_pairs.head(15).style.format({"rate_within_real_class": "{:.1%}"}))

Pares de confusión más frecuentes

## 15 Análisis de errores

La galería ordena errores por confianza. Los errores de alta confianza son especialmente informativos: pueden señalar similitud morfológica entre razas, fondos dominantes, encuadres extremos, o ejemplos atípicos. Este análisis no se usa para reajustar el modelo después de abrir test.

In [22]:
test_images = np.concatenate([images.numpy() for images, _ in test_batches])
prediction_confidence = selected_probabilities.max(axis=1)
wrong_indices = np.flatnonzero(selected_predictions != y_true)
wrong_indices = wrong_indices[np.argsort(prediction_confidence[wrong_indices])[::-1]]

gallery_count = min(16, len(wrong_indices))
if gallery_count:
    rows = int(np.ceil(gallery_count / 4))
    fig, axes = plt.subplots(rows, 4, figsize=(14, 3.6 * rows))
    axes = np.atleast_1d(axes).ravel()
    for ax in axes:
        ax.axis("off")
    for ax, index in zip(axes, wrong_indices[:gallery_count]):
        ax.imshow(test_images[index])
        ax.set_title(
            f"Real: {CLASS_NAMES[y_true[index]]}\n"
            f"Pred: {CLASS_NAMES[selected_predictions[index]]}\n"
            f"Confianza: {prediction_confidence[index]:.1%}",
            fontsize=9,
        )
        ax.axis("off")
    plt.suptitle(f"Errores de mayor confianza — {best_validation_model}", y=1.01)
    plt.tight_layout()
    fig.savefig(ARTIFACT_DIR / "selected_model_error_gallery.png", dpi=170, bbox_inches="tight")
    plt.show()
else:
    print("No hubo errores en test.")

## 16 Impacto de Data augmentation

La siguiente comparación aísla augmentation porque ambos modelos comparten arquitectura e hiperparámetros. Una mejora en validation/test junto con una brecha de generalización menor apoya que las transformaciones ayudan. Si empeora, debe discutirse si la intensidad elegida distorsiona señales finas de la raza.

In [23]:
ablation_names = ["cnn_regularized_no_aug", "cnn_regularized_aug"]
ablation = validation_results[validation_results["model"].isin(ablation_names)].merge(
    test_results[["model", "test_accuracy", "macro_f1"]], on="model", how="left"
).set_index("model").loc[ablation_names]
display(ablation.style.format({
    "train_accuracy_at_best": "{:.3f}", "val_accuracy_history": "{:.3f}",
    "val_accuracy_checkpoint": "{:.3f}", "generalization_gap": "{:.3f}",
    "test_accuracy": "{:.3f}", "macro_f1": "{:.3f}", "training_seconds": "{:.1f}"
}))

augmentation_delta = (
    ablation.loc["cnn_regularized_aug", "test_accuracy"]
    - ablation.loc["cnn_regularized_no_aug", "test_accuracy"]
)
direction = "mejoró" if augmentation_delta > 0 else "redujo"
print(f"Data augmentation {direction} el test accuracy en {abs(augmentation_delta):.2%} puntos porcentuales.")

Data augmentation redujo el test accuracy en 9.24% puntos porcentuales.

## 17 Conclusiones

Las conclusiones siguientes se construyen con resultados observados. El criterio académico se considera cumplido solo si el modelo seleccionado por validation supera 85% en test y sus curvas no muestran una brecha de generalización relevante. El diagnóstico automático es una ayuda; la interpretación final debe considerar conjuntamente curvas, métricas por clase y errores visuales.

In [24]:
selected_validation = validation_results[
    validation_results["model"] == best_validation_model
].iloc[0]
selected_test = test_results[test_results["model"] == best_validation_model].iloc[0]

objective_met = selected_test["test_accuracy"] >= 0.85
curve_ok = selected_validation["curve_diagnosis"] == "sin evidencia fuerte en las curvas"
fc_accuracy = float(test_results.loc[test_results["model"] == "fc_baseline", "test_accuracy"].iloc[0])
cnn_gain = float(selected_test["test_accuracy"] - fc_accuracy)

print("CONCLUSIÓN BASADA EN LA EJECUCIÓN")
print(f"1. El modelo seleccionado por validation fue {best_validation_model}.")
print(f"2. Alcanzó {selected_test['test_accuracy']:.2%} de accuracy y {selected_test['macro_f1']:.2%} de macro-F1 en test.")
print(f"3. El umbral académico de 85% {'se cumplió' if objective_met else 'no se cumplió'}.")
print(f"4. El diagnóstico de curvas fue: {selected_validation['curve_diagnosis']}.")
print(f"5. Frente al Fully Connected, el modelo seleccionado cambió el accuracy en {cnn_gain:+.2%} puntos porcentuales.")
print(f"6. La ablación midió un efecto de augmentation de {augmentation_delta:+.2%} puntos porcentuales en test.")
print("7. Las clases y pares concretos que requieren mayor atención aparecen en las tablas anteriores.")

if objective_met and curve_ok:
    print("\nVeredicto: el objetivo se cumple sin evidencia fuerte de overfitting o underfitting en las curvas.")
elif objective_met:
    print("\nVeredicto: se supera 85%, pero las curvas requieren una discusión crítica antes de afirmar buena generalización.")
else:
    print("\nVeredicto: la ejecución aún no satisface el umbral; no debe reportarse como cumplido.")

CONCLUSIÓN BASADA EN LA EJECUCIÓN
1. El modelo seleccionado por validation fue mobilenet_finetuned.
2. Alcanzó 86.14% de accuracy y 85.10% de macro-F1 en test.
3. El umbral académico de 85% se cumplió.
4. El diagnóstico de curvas fue: sin evidencia fuerte en las curvas.
5. Frente al Fully Connected, el modelo seleccionado cambió el accuracy en +82.61% puntos porcentuales.
6. La ablación midió un efecto de augmentation de -9.24% puntos porcentuales en test.
7. Las clases y pares concretos que requieren mayor atención aparecen en las tablas anteriores.

Veredicto: el objetivo se cumple sin evidencia fuerte de overfitting o underfitting en las curvas.

## 18 Exportación de resultados y entrega

Esta celda genera un informe Markdown con las métricas reales y empaqueta checkpoints, historiales, tablas y figuras. El notebook ejecutado puede exportarse a PDF desde el navegador para conservar la narrativa completa y las salidas visibles.

In [25]:
def markdown_table(frame, columns):
    header = "| " + " | ".join(columns) + " |"
    separator = "|" + "|".join(["---"] * len(columns)) + "|"
    rows = []
    for _, row in frame[columns].iterrows():
        values = []
        for column in columns:
            value = row[column]
            if isinstance(value, (float, np.floating)):
                values.append(f"{value:.4f}")
            else:
                values.append(str(value))
        rows.append("| " + " | ".join(values) + " |")
    return "\n".join([header, separator, *rows])

worst_classes = per_class_report.reset_index().head(10)
report_text = f'''# Informe de resultados Oxford IIIT Pet

## Resultado principal

El modelo seleccionado exclusivamente con validation fue **{best_validation_model}**. En test obtuvo **{selected_test['test_accuracy']:.2%} de accuracy** y **{selected_test['macro_f1']:.2%} de macro F1**. El umbral de 85% **{'se cumplió' if objective_met else 'no se cumplió'}**. El diagnóstico de curvas fue **{selected_validation['curve_diagnosis']}**.

## Comparación final

{markdown_table(test_results, ['model', 'selected_by_validation', 'test_accuracy', 'macro_precision', 'macro_recall', 'macro_f1'])}

## Ablación de augmentation

La diferencia controlada en test accuracy fue {augmentation_delta:+.2%} puntos porcentuales.

## Clases con menor F1

{markdown_table(worst_classes, ['class_name', 'precision', 'recall', 'f1-score', 'support'])}

## Pares de confusión principales

{markdown_table(confusion_pairs.head(10), ['real', 'predicted', 'errors', 'rate_within_real_class'])}

## Trazabilidad

La configuración completa está en `run_config.json`; los historiales y checkpoints permiten reproducir las figuras y predicciones sin reentrenar. Test se abrió después de seleccionar el modelo con validation.
'''
report_text = "\n".join(line.strip() for line in report_text.splitlines()) + "\n"
(ARTIFACT_DIR / "informe_resultados.md").write_text(report_text, encoding="utf-8")

archive_path = Path.cwd() / "entrega_oxford_pet.zip"
with ZipFile(archive_path, "w", compression=ZIP_DEFLATED) as archive:
    for folder in (MODEL_DIR, ARTIFACT_DIR):
        for path in folder.rglob("*"):
            if path.is_file():
                archive.write(path, arcname=f"{folder.name}/{path.relative_to(folder)}")

print("Informe:", ARTIFACT_DIR / "informe_resultados.md")
print("Paquete de entrega:", archive_path)

try:
    from google.colab import files
    print("En Colab puede descargar el paquete con: files.download(str(archive_path))")
except ImportError:
    pass

Informe: /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/artifacts/informe_resultados.md
Paquete de entrega: /Users/enriquemunoz/dev/Maestria IA/Ai-Oxford-IIIT-Pet-Dataset/entrega_oxford_pet.zip

## Referencias

- Oxford Visual Geometry Group. *The Oxford-IIIT Pet Dataset*.
- TensorFlow Datasets. *Oxford IIIT Pet catalog*.
- TensorFlow. *Transfer learning and fine tuning*.
- Sandler et al. (2018). *MobileNetV2: Inverted Residuals and Linear Bottlenecks*.

Los enlaces originales del enunciado y el material suministrado se conservan en la carpeta `materiales` del repositorio.